version: '3.7'
services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment:
            - ENVIRONMENT=production
            - DEBUG=0
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
            - redis
    db:
        image: postgres:12
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=jobBoardDB
            - POSTGRES_PASSWORD=PAKarmy@98
    redis:
      image: redis:latest
      ports:
      - '6379:6379'

volumes:
    postgres_data: